league_oauth2_server:
    authorization_server:
        private_key: '%env(resolve:OAUTH_PRIVATE_KEY)%'
        private_key_passphrase: '%env(resolve:OAUTH_PASSPHRASE)%'
        encryption_key: '%env(resolve:OAUTH_ENCRYPTION_KEY)%'
        access_token_ttl: PT1M # 5 minutes
        refresh_token_ttl: P1M # 1 month
    resource_server:
        public_key: '%env(resolve:OAUTH_PUBLIC_KEY)%'
    scopes:
        available: ['spice']
        default: ['spice']
    persistence:
        doctrine: null

when@test:
    league_oauth2_server:
        persistence:
            doctrine: null
